//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonuriDeCasa_Produse
    {
        public int Id { get; set; }
        public Nullable<int> BonId { get; set; }
        public Nullable<int> ProdusId { get; set; }
        public decimal Cantitate { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual BonuriDeCasa BonuriDeCasa { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
