//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferte
    {
        public int Id { get; set; }
        public string MotivOferta { get; set; }
        public Nullable<int> ProdusId { get; set; }
        public decimal ProcentReducere { get; set; }
        public System.DateTime DataDeLa { get; set; }
        public System.DateTime DataPanaLa { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Produse Produse { get; set; }
    }
}
