//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produse()
        {
            this.BonuriDeCasa_Produse = new HashSet<BonuriDeCasa_Produse>();
            this.Oferte = new HashSet<Oferte>();
            this.Stocuri = new HashSet<Stocuri>();
        }
    
        public int Id { get; set; }
        public string NumeProdus { get; set; }
        public string CodDeBare { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> ProducatorId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonuriDeCasa_Produse> BonuriDeCasa_Produse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferte> Oferte { get; set; }
        public virtual Producatori Producatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocuri> Stocuri { get; set; }
    }
}
