//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocuri
    {
        public int Id { get; set; }
        public Nullable<int> ProdusId { get; set; }
        public decimal Cantitate { get; set; }
        public string UnitateDeMasura { get; set; }
        public System.DateTime DataAprovizionarii { get; set; }
        public Nullable<System.DateTime> DataExpirarii { get; set; }
        public decimal PretAchizitie { get; set; }
        public decimal PretDeVanzare { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Produse Produse { get; set; }
    }
}
